### ISSUE TITLE
Prepare Andrew Do's notebook on text analysis

### ISSUE THREAD

**Issue by SamLau95** [DS-100/textbook#16]
Andrew Do created a notebook explaining text analysis here: https://github.com/DS-100/textbook/blob/master/ch08/working_with_text.ipynb .

It's not quite in a state where it's ready to include in the textbook but has most of the necessary pieces. We would like to edit it, split it up into a couple sections, and put it into the textbook.

**Comment by zhunation** [comment]
Would like to work on this

**Comment by SamLau95** [comment]
Done! https://www.textbook.ds100.org/ch08/text_intro.html
