### ISSUE TITLE
11.2 LaTeX not rendering

### ISSUE THREAD

**Issue by junseo-park** [DS-100/textbook#44]
LaTeX not rendering properly in [11.2 Defining Gradient Descent/Minimizing the Huber cost](https://www.textbook.ds100.org/ch11/gradient_descent_define.html#Minimizing-the-Huber-cost). Not sure why; the jupyter notebook looks fine. Would this be resolved by re-running `make`?

**Comment by junseo-park** [comment]
@SamLau95

**Comment by allenshen5** [comment]
I have run into this issue as well several times; there also seems to be unnecessary scrollbars on a lot of the latex. I think the conversion script thinks part of the latex is code when it is supposed to be markdown or something.

**Comment by allenshen5** [comment]
There is a similar issue at the end of 16.3; I have included a temp fix for this in my PR as well.

**Comment by allenshen5** [comment]
It looks like the new Jekyll build fixed this for the most part! I will be closing this for now, but feel free to reopen if this comes up again.

**Comment by junseo-park** [comment]
@allenshen5 looks like this issue is back - https://www.textbook.ds100.org/ch/11/gradient_descent_define.html#Minimizing-the-Huber-loss
