### ISSUE TITLE
some rendering error in 14.2

### ISSUE THREAD

**Issue by tjann** [DS-100/textbook#45]
![image](https://user-images.githubusercontent.com/18621425/41814722-0f41f606-770b-11e8-9e89-c5d9eb22ac88.png)

**Comment by tjann** [comment]
looks like it's the "—" 
https://github.com/DS-100/textbook/blob/master/notebooks/ch14/bias_random_vars.ipynb

**Comment by tjann** [comment]
while you're at it, this should also be plural:

**Comment by allenshen5** [comment]
Pulling from master and rerunning the conversion script should fix the former issue.

**Comment by zhunation** [comment]
This seems to be ok here, https://www.textbook.ds100.org/ch14/bias_risk.html

**Comment by allenshen5** [comment]
Yeah, looks like #31 fixed the former issue, although the dash seems shorter than the Unicode dash at the end of 14.1.

**Comment by allenshen5** [comment]
Fixed by #50
